### ISSUE TITLE
Initial feedrate set to 10%?

### ISSUE THREAD

**Issue by mylife4aiurr** [skellatore/palette2-plugin#2]
Prusa MK3 - firmware 3.5.0-1749
DIY Canvas plugin ver. 1.2.0
Your plugin ver. 1.2.0-P2PP-RC1
Palette 2 pro: firmware 2.0.2

Palette 2 plugin screen reports speed normal... however mk3 lcd screen says 10% - printing is very slow. Attempts to change feedrate to 100% succeed for a short period of time then plugin reverts speed back to 10%

**Comment by skellatore** [comment]
This has been resolved.
