### ISSUE TITLE
Repeated Preheat Warnings

### ISSUE THREAD

**Issue by mylife4aiurr** [skellatore/palette2-plugin#3]
Was warned 20+ times to preheat. I preheat after 1st warning. Still warned repeatedly. No option to cancel future warns. Once printer and palette is ready - cursor focus isnt there, because plugin is still warning in the background but new palette2 plugin warning?? takes a 2mins for you to be able to click ok for new warning.

**Comment by skellatore** [comment]
This has been resolved.
